# Generated by Django 4.2.6 on 2023-10-09 22:57

import APP.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bd1_Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'db_table': 'Requerimientos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bd2_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'Areas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bd3_Ps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=252)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Personal sistema',
                'verbose_name_plural': 'Personal de sistemas',
                'db_table': 'Personal de sistemas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bd4_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=252)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.bd2_area')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket_Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicacion_breve', models.CharField(max_length=255)),
                ('explicacion_larga', models.TextField()),
                ('fecha_solicitud', models.DateField(default=APP.models.fecha_estimada_default)),
                ('estatus', models.CharField(choices=[('EA', 'En espera de asignación'), ('PT', 'Pendiente'), ('EP', 'En proceso'), ('OK', 'Realizado')], default='EA', max_length=25)),
                ('fecha_Vencimiento', models.DateField(default=APP.models.fecha_estimada_default)),
                ('prioridad', models.CharField(choices=[('A', 'Alta'), ('B', 'Media'), ('C', 'Baja')], default='B', max_length=10)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.bd2_area')),
                ('asignacion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.bd3_ps')),
                ('requerimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.bd1_requerimiento')),
                ('usuario_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.bd4_user')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'Tickets',
                'ordering': ['id'],
            },
        ),
    ]
